/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/claim-drafts/{draftId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an unsubmitted draft document */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "X-Draft-Token": string;
                };
                path: {
                    draftId: string;
                    documentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document scheduled for deletion. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Draft expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claim-drafts/{draftId}/upload-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize a direct upload to Vercel Private Blob */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Draft-Token": string;
                };
                path: {
                    draftId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadTokenRequest"];
                };
            };
            responses: {
                /** @description Upload authorization. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadTokenResponse"];
                    };
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Draft expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description File is too large. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description File media type is not allowed. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Evidence rules are not satisfied. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recall-campaigns/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently published public campaign configuration */
        get: {
            parameters: {
                query?: {
                    locale?: "en-US";
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published campaign content. */
                200: {
                    headers: {
                        "Content-Language"?: string;
                        /** @description Published version entity tag. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignResponse"];
                    };
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recall-campaigns/{slug}/claim-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an expiring anonymous upload draft */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Draft created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimDraftResponse"];
                    };
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recall-campaigns/{slug}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a consumer recall claim */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClaimSubmissionRequest"];
                };
            };
            responses: {
                /** @description Claim submitted. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimSubmissionResponse"];
                    };
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Idempotency conflict or draft already used. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Draft expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign, product, evidence, or conditional fields are invalid. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recall-campaigns/{slug}/product-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a preliminary affected-product check */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCheckRequest"];
                };
            };
            responses: {
                /** @description Preliminary result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductCheckResponse"];
                    };
                };
                /** @description Invalid request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Campaign or resource not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unexpected server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The contract exists, but the Phase 1 skeleton has no provider implementation. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description A required dependency is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CampaignResponse: {
            campaign: {
                code: string;
                defaultLocale: string;
                evidenceRequirements: components["schemas"]["EvidenceRequirement"][];
                hazard: string;
                immediateAction: string;
                locale: string;
                products: components["schemas"]["PublicCampaignProduct"][];
                remedies: {
                    code: string;
                    displayName: string;
                }[];
                remedySummary: string;
                slug: string;
                summary: string;
                support: {
                    /** Format: email */
                    email: string;
                    hours: string;
                    phone: string;
                };
                title: string;
                version: number;
            };
        };
        ClaimDraftResponse: {
            /** Format: uuid */
            draftId: string;
            draftToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ClaimSubmissionRequest: {
            consents: {
                /** @enum {boolean} */
                accepted: true;
                textVersion: string;
                /** @enum {string} */
                type: "privacy_notice" | "information_accuracy";
            }[];
            consumer: {
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                mailingAddress: components["schemas"]["ConsumerAddress"];
                phone?: string;
            };
            documentIds: string[];
            /** Format: uuid */
            draftId: string;
            draftToken: string;
            /** @enum {string} */
            incidentAnswer: "no" | "yes" | "unsure";
            incidentDetails?: components["schemas"]["IncidentDetailsInput"];
            /** @enum {string} */
            locale: "en-US";
            products: components["schemas"]["ClaimedProductInput"][];
            remedyCode: string;
        };
        ClaimSubmissionResponse: {
            caseReference: string;
            /** @enum {string} */
            emailStatus: "queued";
            nextStep: string;
            /** Format: date-time */
            submittedAt: string;
        };
        ClaimedProductInput: {
            /** Format: uuid */
            campaignProductId: string;
            dateCode: string;
            flavor: string;
            lotCode: string;
            orderNumber?: string;
            /** @enum {string} */
            purchaseChannel: "amazon" | "tiktok" | "koi" | "retailer" | "gift" | "other";
            purchaseDate?: string;
            quantity: number;
            shape: string;
        };
        ConsumerAddress: {
            city: string;
            /** @default US */
            countryCode: string;
            line1: string;
            line2?: string;
            postalCode: string;
            state: string;
        };
        EvidenceRequirement: {
            allowedMimeTypes: string[];
            /** @enum {string} */
            category: "product_photo" | "proof_of_purchase" | "incident_evidence";
            instructions: string;
            maximumFileSizeBytes: number;
            maximumFiles: number;
            minimumFiles: number;
            required: boolean;
        };
        IncidentDetailsInput: {
            eventTypes?: ("injury" | "illness" | "choking" | "ingestion" | "fire" | "overheating" | "property_damage" | "near_miss" | "other" | "unknown")[];
            /** @enum {string} */
            injurySeverity?: "none" | "minor" | "medical_attention" | "hospitalized" | "death" | "unknown";
            /** @enum {string} */
            medicalTreatment?: "none" | "first_aid" | "outpatient" | "emergency" | "hospitalized" | "unknown";
            narrative: string;
            occurredDate?: string;
            /** @default false */
            occurredDateUnknown: boolean;
            /** @enum {string} */
            usedAsIntended?: "yes" | "no" | "unknown";
        };
        ProblemDetails: {
            detail: string;
            errors?: {
                message: string;
                path: string;
            }[];
            instance?: string;
            requestId?: string;
            status: number;
            title: string;
            /** Format: uri */
            type: string;
        };
        ProductCheckRequest: {
            dateCode: string;
            flavor: string;
            lotCode: string;
            shape: string;
        };
        ProductCheckResponse: {
            checkedCampaignVersion: number;
            /** @enum {string} */
            disclaimer: "This check is preliminary and is not a final eligibility decision.";
            message: string;
            /** @enum {string} */
            result: "potential_match" | "not_matched" | "manual_review";
        };
        PublicCampaignProduct: {
            affectedLots: {
                attributes: {
                    [key: string]: unknown;
                };
                dateCode: string;
                lotCode: string;
            }[];
            brand: string;
            flavors: string[];
            name: string;
            /** Format: uuid */
            productId: string;
            shapes: string[];
            sku: string;
        };
        UploadTokenRequest: {
            /** @enum {string} */
            category: "product_photo" | "proof_of_purchase" | "incident_evidence";
            fileName: string;
            mimeType: string;
            sizeBytes: number;
        };
        UploadTokenResponse: {
            clientToken: string;
            /** Format: uuid */
            documentId: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uri */
            uploadUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
